--------------------------------------------------------
--  File created - Thursday-October-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure PRC_BITACORA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "PRC_BITACORA" (PNOMTABLA VARCHAR2, PVALOLD VARCHAR2, PVALNEW VARCHAR2, PATRIBUTO VARCHAR, PATRILLAVE VARCHAR2, PATRIORA VARCHAR2, PTIPO VARCHAR2) IS 
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
INSERT INTO BITACORA (CORRELATIVO, NOMBRE_TABLA, USUARIO, FECHA, VALOR_ANTIGUO, VALOR_NUEVO, ATRIBUTO, ATRIBUTO_LLAVE, ATRIBUTO_ORACLE, TIPO) 
VALUES (SQC_BITACORA.NEXTVAL, PNOMTABLA, USER, SYSDATE, PVALOLD, PVALNEW, PATRIBUTO, PATRILLAVE, PATRIORA,PTIPO);
COMMIT;
END;

/
