--------------------------------------------------------
--  File created - Friday-October-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Trigger TRG_BANCO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_BANCO" 
BEFORE INSERT ON BANCO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('BANCO', NULL, :NEW.NOMBRE_BANCO, 'NOMBRE_BANCO', :NEW.ID_BANCO,  :NEW.ROWID, 'INSERT'); 
END;

/
ALTER TRIGGER "TRG_BANCO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BANCO_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_BANCO_DELETE" 
AFTER DELETE ON BANCO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('BANCO', :OLD.NOMBRE_BANCO, NULL, 'NOMBRE_BANCO', :OLD.ID_BANCO, :OLD.ROWID, 'DELETE'); 
END;

/
ALTER TRIGGER "TRG_BANCO_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BANCO_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_BANCO_UPDATE" 
AFTER UPDATE ON BANCO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('BANCO', :OLD.NOMBRE_BANCO, :NEW.NOMBRE_BANCO, 'NOMBRE_BANCO', :NEW.ID_BANCO, :OLD.ROWID, 'UPDATE');
END;

/
ALTER TRIGGER "TRG_BANCO_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CONTACTO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_CONTACTO" 
BEFORE INSERT ON CONTACTO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('CONTACTO', NULL, :NEW.ID_PROVEEDOR, 'ID_PROVEEDOR', :NEW.ID_CONTACTO,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('CONTACTO', NULL, :NEW.ID_PERSONA, 'ID_PERSONA', :NEW.ID_CONTACTO,  :NEW.ROWID, 'INSERT'); 

END;



/
ALTER TRIGGER "TRG_CONTACTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CONTACTO_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_CONTACTO_DELETE" 
AFTER DELETE ON CONTACTO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('CONTACTO', :OLD.ID_PROVEEDOR, NULL, 'ID_PROVEEDOR', :OLD.ID_CONTACTO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('CONTACTO', :OLD.ID_PERSONA, NULL, 'ID_PERSONA', :OLD.ID_CONTACTO, :OLD.ROWID, 'DELETE'); 
END;



/
ALTER TRIGGER "TRG_CONTACTO_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CONTACTO_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_CONTACTO_UPDATE" 
AFTER UPDATE ON CONTACTO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('CONTACTO', :OLD.ID_PROVEEDOR, :NEW.ID_PROVEEDOR, 'ID_PROVEEDOR', :NEW.ID_CONTACTO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('CONTACTO', :OLD.ID_PERSONA, :NEW.ID_PERSONA, 'ID_PERSONA', :NEW.ID_CONTACTO, :OLD.ROWID, 'UPDATE'); 
END;



/
ALTER TRIGGER "TRG_CONTACTO_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CUENTA_BANCO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_CUENTA_BANCO" 
BEFORE INSERT ON CUENTA_BANCO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('CUENTA_BANCO', NULL, :NEW.ID_TIPO_CUENTA, 'ID_TIPO_CUENTA', :NEW.ID_CUENTA_BANCO,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('CUENTA_BANCO', NULL, :NEW.ID_BANCO, 'ID_BANCO', :NEW.ID_CUENTA_BANCO,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('CUENTA_BANCO', NULL, :NEW.NO_CUENTA, 'NO_CUENTA', :NEW.ID_CUENTA_BANCO,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('CUENTA_BANCO', NULL, :NEW.SALDO, 'SALDO', :NEW.ID_CUENTA_BANCO,  :NEW.ROWID, 'INSERT'); 
END;

/
ALTER TRIGGER "TRG_CUENTA_BANCO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CUENTA_BANCO_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_CUENTA_BANCO_DELETE" 
AFTER DELETE ON CUENTA_BANCO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('CUENTA_BANCO', :OLD.ID_TIPO_CUENTA, NULL, 'ID_TIPO_CUENTA', :OLD.ID_CUENTA_BANCO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('CUENTA_BANCO', :OLD.ID_BANCO, NULL, 'ID_BANCO', :OLD.ID_CUENTA_BANCO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('CUENTA_BANCO', :OLD.NO_CUENTA, NULL, 'NO_CUENTA', :OLD.ID_CUENTA_BANCO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('CUENTA_BANCO', :OLD.SALDO, NULL, 'SALDO', :OLD.ID_CUENTA_BANCO, :OLD.ROWID, 'DELETE'); 
END;

/
ALTER TRIGGER "TRG_CUENTA_BANCO_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CUENTA_BANCO_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_CUENTA_BANCO_UPDATE" 
AFTER UPDATE ON CUENTA_BANCO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('CUENTA_BANCO', :OLD.ID_TIPO_CUENTA, :NEW.ID_TIPO_CUENTA, 'ID_TIPO_CUENTA', :NEW.ID_CUENTA_BANCO, :OLD.ROWID, 'UPDATE');
PRC_BITACORA('CUENTA_BANCO', :OLD.ID_BANCO, :NEW.ID_BANCO, 'ID_BANCO', :NEW.ID_CUENTA_BANCO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('CUENTA_BANCO', :OLD.NO_CUENTA, :NEW.NO_CUENTA, 'NO_CUENTA', :NEW.ID_CUENTA_BANCO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('CUENTA_BANCO', :OLD.SALDO, :NEW.SALDO, 'SALDO', :NEW.ID_CUENTA_BANCO, :OLD.ROWID, 'UPDATE'); 

END;

/
ALTER TRIGGER "TRG_CUENTA_BANCO_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CUENTA_PAGAR
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_CUENTA_PAGAR" 
AFTER INSERT ON CUENTA_PAGAR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('CUENTA_PAGAR', NULL, :NEW.ID_FACTURA_PROVEEDOR, 'ID_FACTURA_PROVEEDOR', :NEW.ID_CUENTA_PAGAR, :NEW.ROWID, 'INSERT'); 
END;




/
ALTER TRIGGER "TRG_CUENTA_PAGAR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CUENTA_PAGAR_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_CUENTA_PAGAR_DELETE" 
AFTER DELETE ON CUENTA_PAGAR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('CUENTA_PAGAR',  :OLD.ID_FACTURA_PROVEEDOR, NULL, 'ID_FACTURA_PROVEEDOR', :OLD.ID_CUENTA_PAGAR, :OLD.ROWID, 'DELETE'); 
END;





/
ALTER TRIGGER "TRG_CUENTA_PAGAR_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CUENTA_PAGAR_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_CUENTA_PAGAR_UPDATE" 
AFTER UPDATE ON CUENTA_PAGAR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('CUENTA_PAGAR',  :OLD.ID_FACTURA_PROVEEDOR, :NEW.ID_FACTURA_PROVEEDOR, 'ID_FACTURA_PROVEEDOR', :NEW.ID_CUENTA_PAGAR, :OLD.ROWID, 'UPDATE'); 
END;




/
ALTER TRIGGER "TRG_CUENTA_PAGAR_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_COMPRA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_DETALLE_COMPRA" 
BEFORE INSERT ON DETALLE_COMPRA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('DETALLE_COMPRA', NULL, :NEW.ID_ORDEN_COMPRA, 'ID_ORDEN_COMPRA', :NEW.ID_DETALLE_COMPRA, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('DETALLE_COMPRA', NULL, :NEW.ID_PRODUCTO, 'ID_PRODUCTO', :NEW.ID_DETALLE_COMPRA, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('DETALLE_COMPRA', NULL, :NEW.CANTIDAD, 'CANTIDAD', :NEW.ID_DETALLE_COMPRA, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('DETALLE_COMPRA', NULL, :NEW.PRECIO, 'PRECIO', :NEW.ID_DETALLE_COMPRA, :NEW.ROWID, 'INSERT'); 
END;




/
ALTER TRIGGER "TRG_DETALLE_COMPRA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_COMPRA_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_DETALLE_COMPRA_DELETE" 
AFTER DELETE ON DETALLE_COMPRA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('DETALLE_COMPRA',:OLD.ID_ORDEN_COMPRA, NULL, 'ID_ORDEN_COMPRA', :OLD.ID_DETALLE_COMPRA,:OLD.ROWID, 'DELETE'); 
PRC_BITACORA('DETALLE_COMPRA',:OLD.ID_PRODUCTO, NULL, 'ID_PRODUCTO', :OLD.ID_DETALLE_COMPRA, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('DETALLE_COMPRA',  :OLD.CANTIDAD, NULL, 'CANTIDAD', :OLD.ID_DETALLE_COMPRA, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('DETALLE_COMPRA',:OLD.PRECIO, NULL, 'PRECIO', :OLD.ID_DETALLE_COMPRA, :OLD.ROWID, 'DELETE'); 
END;





/
ALTER TRIGGER "TRG_DETALLE_COMPRA_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_COMPRA_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_DETALLE_COMPRA_UPDATE" 
AFTER UPDATE ON DETALLE_COMPRA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('DETALLE_COMPRA',:OLD.ID_ORDEN_COMPRA, :NEW.ID_ORDEN_COMPRA, 'ID_ORDEN_COMPRA', :NEW.ID_DETALLE_COMPRA,:OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('DETALLE_COMPRA',:OLD.ID_PRODUCTO, :NEW.ID_PRODUCTO, 'ID_PRODUCTO', :NEW.ID_DETALLE_COMPRA, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('DETALLE_COMPRA',  :OLD.CANTIDAD, :NEW.CANTIDAD, 'CANTIDAD', :NEW.ID_DETALLE_COMPRA, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('DETALLE_COMPRA',:OLD.PRECIO, :NEW.PRECIO, 'PRECIO', :NEW.ID_DETALLE_COMPRA, :OLD.ROWID, 'UPDATE'); 
END;





/
ALTER TRIGGER "TRG_DETALLE_COMPRA_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_RECEPCION
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_DETALLE_RECEPCION" 
AFTER INSERT ON DETALLE_RECEPCION
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE 
ID_P NUMBER(15):= 0;
ID_S NUMBER(15):=0;
ID_E_S NUMBER(15):=0;
QUANTITY NUMBER(15):=0;
SWITCH NUMBER(1):=0;
C_P NUMBER(15) := 0;
BEGIN
C_P := :NEW.CANTIDAD;
 BEGIN
    SELECT ID_PRODUCTO
    INTO ID_P
    FROM DETALLE_COMPRA
    WHERE ID_DETALLE_COMPRA =:NEW.ID_DETALLE_COMPRA;

    SELECT ID_SUCURSAL
    INTO ID_S
    FROM SUCURSAL
    WHERE ID_SUCURSAL =:NEW.ID_SUCURSAL;
 END;
 BEGIN
   SELECT ID_EXISTENCIAS_SUCURSAL, EXISTENCIAS
   INTO ID_E_S, QUANTITY
   FROM EXISTENCIAS_SUCURSAL
   WHERE ID_PRODUCTO = ID_P;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         --RAISE_APPLICATION_ERROR(-20001,'No existe previo registro del producto en esta sucursal, por lo tanto se creara el registro de tal');
         SWITCH:=1;
          INSERT INTO EXISTENCIAS_SUCURSAL(ID_EXISTENCIAS_SUCURSAL, ID_PRODUCTO, ID_SUCURSAL, EXISTENCIAS)
          VALUES(SQC_EXISTENCIAS_SUCURSAL.NEXTVAL,ID_P, ID_S, C_P);

      WHEN TOO_MANY_ROWS THEN
         RAISE_APPLICATION_ERROR(-20002,'El PRODUCTO existe mas de una vez');
      WHEN OTHERS THEN
         RAISE_APPLICATION_ERROR(-20003,'Error al insertar el EXISTENCIAS DE PRODUCTOS '||SQLERRM);  
 END;
 IF SWITCH = 0 THEN
     UPDATE EXISTENCIAS_SUCURSAL
   SET EXISTENCIAS = (C_P+ EXISTENCIAS)
   WHERE ID_EXISTENCIAS_SUCURSAL = ID_E_S;
   END IF;
 PRC_BITACORA('DETALLE_RECEPCION', NULL, :NEW.ID_RECEPCION, 'ID_RECEPCION', :NEW.ID_DETALLE_RECEPCION, :NEW.ROWID, 'INSERT'); 
           PRC_BITACORA('DETALLE_RECEPCION', NULL, :NEW.ID_DETALLE_COMPRA, 'ID_DETALLE_COMPRA', :NEW.ID_DETALLE_RECEPCION, :NEW.ROWID, 'INSERT'); 
            PRC_BITACORA('DETALLE_RECEPCION', NULL, :NEW.ID_SUCURSAL, 'ID_SUCURSAL', :NEW.ID_DETALLE_RECEPCION, :NEW.ROWID, 'INSERT'); 
             PRC_BITACORA('DETALLE_RECEPCION', NULL, :NEW.PRECIO, 'PRECIO', :NEW.ID_DETALLE_RECEPCION, :NEW.ROWID, 'INSERT'); 
              PRC_BITACORA('DETALLE_RECEPCION', NULL, :NEW.CANTIDAD, 'CANTIDAD', :NEW.ID_DETALLE_RECEPCION, :NEW.ROWID, 'INSERT'); 
END;




/
ALTER TRIGGER "TRG_DETALLE_RECEPCION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_RECEPCION_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_DETALLE_RECEPCION_DELETE" 
AFTER DELETE ON DETALLE_RECEPCION
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
 PRC_BITACORA('DETALLE_RECEPCION',:OLD.ID_RECEPCION, NULL, 'ID_RECEPCION', :OLD.ID_DETALLE_RECEPCION, :OLD.ROWID, 'DELETE'); 
           PRC_BITACORA('DETALLE_RECEPCION', :OLD.ID_DETALLE_COMPRA, NULL, 'ID_DETALLE_COMPRA', :OLD.ID_DETALLE_RECEPCION, :OLD.ROWID, 'DELETE'); 
            PRC_BITACORA('DETALLE_RECEPCION',:OLD.ID_SUCURSAL, NULL, 'ID_SUCURSAL', :OLD.ID_DETALLE_RECEPCION, :OLD.ROWID, 'DELETE'); 
             PRC_BITACORA('DETALLE_RECEPCION', :OLD.PRECIO, NULL, 'PRECIO', :OLD.ID_DETALLE_RECEPCION, :OLD.ROWID, 'DELETE'); 
              PRC_BITACORA('DETALLE_RECEPCION', :OLD.CANTIDAD, NULL, 'CANTIDAD', :OLD.ID_DETALLE_RECEPCION, :OLD.ROWID, 'DELETE'); 
END;




/
ALTER TRIGGER "TRG_DETALLE_RECEPCION_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_RECEPCION_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_DETALLE_RECEPCION_UPDATE" 
AFTER UPDATE ON DETALLE_RECEPCION
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
 PRC_BITACORA('DETALLE_RECEPCION',:OLD.ID_RECEPCION, :NEW.ID_RECEPCION, 'ID_RECEPCION', :NEW.ID_DETALLE_RECEPCION, :OLD.ROWID, 'UPDATE'); 
           PRC_BITACORA('DETALLE_RECEPCION', :OLD.ID_DETALLE_COMPRA, :NEW.ID_DETALLE_COMPRA, 'ID_DETALLE_COMPRA', :NEW.ID_DETALLE_RECEPCION, :OLD.ROWID, 'UPDATE'); 
            PRC_BITACORA('DETALLE_RECEPCION',:OLD.ID_SUCURSAL, :NEW.ID_SUCURSAL, 'ID_SUCURSAL', :NEW.ID_DETALLE_RECEPCION, :OLD.ROWID, 'UPDATE'); 
             PRC_BITACORA('DETALLE_RECEPCION', :OLD.PRECIO, :NEW.PRECIO, 'PRECIO', :NEW.ID_DETALLE_RECEPCION, :OLD.ROWID, 'UPDATE'); 
              PRC_BITACORA('DETALLE_RECEPCION', :OLD.CANTIDAD, :NEW.CANTIDAD, 'CANTIDAD', :NEW.ID_DETALLE_RECEPCION, :OLD.ROWID, 'UPDATE'); 
END;





/
ALTER TRIGGER "TRG_DETALLE_RECEPCION_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EMPLEADO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_EMPLEADO" 
BEFORE INSERT ON EMPLEADO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('EMPLEADO', NULL, :NEW.ID_PERSONA, 'ID_PERSONA', :NEW.ID_EMPLEADO, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('EMPLEADO', NULL, :NEW.STATUS, 'STATUS', :NEW.ID_EMPLEADO, :NEW.ROWID, 'INSERT'); 
END;



/
ALTER TRIGGER "TRG_EMPLEADO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EMPLEADO_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_EMPLEADO_DELETE" 
AFTER DELETE ON EMPLEADO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('EMPLEADO', :OLD.ID_PERSONA, NULL, 'ID_PERSONA', :OLD.ID_EMPLEADO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('EMPLEADO', :OLD.STATUS, NULL, 'STATUS', :OLD.ID_EMPLEADO, :OLD.ROWID, 'DELETE'); 
END;



/
ALTER TRIGGER "TRG_EMPLEADO_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EMPLEADO_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_EMPLEADO_UPDATE" 
AFTER UPDATE ON EMPLEADO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('EMPLEADO', :OLD.ID_PERSONA, :NEW.ID_PERSONA, 'ID_PERSONA', :NEW.ID_EMPLEADO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('EMPLEADO', :OLD.STATUS, :NEW.STATUS, 'STATUS', :NEW.ID_EMPLEADO, :OLD.ROWID, 'UPDATE'); 
END;



/
ALTER TRIGGER "TRG_EMPLEADO_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EXISTENCIAS_SUCURSAL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_EXISTENCIAS_SUCURSAL" 
BEFORE INSERT ON EXISTENCIAS_SUCURSAL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('EXISTENCIAS_SUCURSAL', NULL, :NEW.ID_PRODUCTO, 'ID_PRODUCTO', :NEW.ID_EXISTENCIAS_SUCURSAL, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('EXISTENCIAS_SUCURSAL', NULL, :NEW.ID_SUCURSAL, 'ID_SUCURSAL', :NEW.ID_EXISTENCIAS_SUCURSAL, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('EXISTENCIAS_SUCURSAL', NULL, :NEW.EXISTENCIAS, 'EXISTENCIAS', :NEW.ID_EXISTENCIAS_SUCURSAL, :NEW.ROWID, 'INSERT');
END;




/
ALTER TRIGGER "TRG_EXISTENCIAS_SUCURSAL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EXISTENCIAS_SUCURSAL_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_EXISTENCIAS_SUCURSAL_DELETE" 
AFTER DELETE ON EXISTENCIAS_SUCURSAL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('EXISTENCIAS_SUCURSAL', :OLD.ID_PRODUCTO, NULL, 'ID_PRODUCTO', :OLD.ID_EXISTENCIAS_SUCURSAL, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('EXISTENCIAS_SUCURSAL', :OLD.ID_SUCURSAL, NULL, 'ID_SUCURSAL', :OLD.ID_EXISTENCIAS_SUCURSAL, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('EXISTENCIAS_SUCURSAL',  :OLD.EXISTENCIAS, NULL, 'EXISTENCIAS', :OLD.ID_EXISTENCIAS_SUCURSAL, :OLD.ROWID, 'DELETE');
END;




/
ALTER TRIGGER "TRG_EXISTENCIAS_SUCURSAL_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_EXISTENCIAS_SUCURSAL_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_EXISTENCIAS_SUCURSAL_UPDATE" 
BEFORE UPDATE ON EXISTENCIAS_SUCURSAL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('EXISTENCIAS_SUCURSAL', :OLD.ID_PRODUCTO, :NEW.ID_PRODUCTO, 'ID_PRODUCTO', :NEW.ID_EXISTENCIAS_SUCURSAL, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('EXISTENCIAS_SUCURSAL', :OLD.ID_SUCURSAL, :NEW.ID_SUCURSAL, 'ID_SUCURSAL', :NEW.ID_EXISTENCIAS_SUCURSAL, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('EXISTENCIAS_SUCURSAL',  :OLD.EXISTENCIAS, :NEW.EXISTENCIAS, 'EXISTENCIAS', :NEW.ID_EXISTENCIAS_SUCURSAL, :OLD.ROWID, 'UPDATE');
END;





/
ALTER TRIGGER "TRG_EXISTENCIAS_SUCURSAL_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_FACTURA_PROVEEDOR
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_FACTURA_PROVEEDOR" 
AFTER INSERT ON FACTURA_PROVEEDOR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE 
ID_FACTURA_PROVEEDOR NUMBER(15):= 0;
BEGIN
ID_FACTURA_PROVEEDOR := :NEW.ID_FACTURA_PROVEEDOR;

PRC_BITACORA('FACTURA_PROVEEDOR', NULL, :NEW.ID_SERVICIO, 'ID_SERVICIO', :NEW.ID_FACTURA_PROVEEDOR,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('FACTURA_PROVEEDOR', NULL, :NEW.ID_ORDEN_COMPRA, 'ID_ORDEN_COMPRA', :NEW.ID_FACTURA_PROVEEDOR,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('FACTURA_PROVEEDOR', NULL, :NEW.NUMERO_FACTURA, 'NUMERO_FACTURA', :NEW.ID_FACTURA_PROVEEDOR,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('FACTURA_PROVEEDOR', NULL, :NEW.FECHA, 'FECHA', :NEW.ID_FACTURA_PROVEEDOR,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('FACTURA_PROVEEDOR', NULL, :NEW.MONTO, 'MONTO', :NEW.ID_FACTURA_PROVEEDOR,  :NEW.ROWID, 'INSERT'); 
INSERT INTO CUENTA_PAGAR (ID_CUENTA_PAGAR, ID_FACTURA_PROVEEDOR) VALUES (SQC_CUENTA_PAGAR.NEXTVAL,ID_FACTURA_PROVEEDOR);
END;




/
ALTER TRIGGER "TRG_FACTURA_PROVEEDOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_FACTURA_PROVEEDOR_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_FACTURA_PROVEEDOR_DELETE" 
AFTER DELETE ON FACTURA_PROVEEDOR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

BEGIN

PRC_BITACORA('FACTURA_PROVEEDOR',:OLD.ID_SERVICIO, NULL, 'ID_SERVICIO', :OLD.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('FACTURA_PROVEEDOR', :OLD.ID_ORDEN_COMPRA, NULL, 'ID_ORDEN_COMPRA', :OLD.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('FACTURA_PROVEEDOR', :OLD.NUMERO_FACTURA, NULL, 'NUMERO_FACTURA', :OLD.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('FACTURA_PROVEEDOR',:OLD.FECHA, NULL, 'FECHA', :OLD.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('FACTURA_PROVEEDOR', :OLD.MONTO, NULL, 'MONTO', :OLD.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'DELETE'); 
END;




/
ALTER TRIGGER "TRG_FACTURA_PROVEEDOR_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_FACTURA_PROVEEDOR_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_FACTURA_PROVEEDOR_UPDATE" 
AFTER UPDATE ON FACTURA_PROVEEDOR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

BEGIN

PRC_BITACORA('FACTURA_PROVEEDOR',:OLD.ID_SERVICIO, :NEW.ID_SERVICIO, 'ID_SERVICIO', :NEW.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('FACTURA_PROVEEDOR', :OLD.ID_ORDEN_COMPRA, :NEW.ID_ORDEN_COMPRA, 'ID_ORDEN_COMPRA', :NEW.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('FACTURA_PROVEEDOR', :OLD.NUMERO_FACTURA, :NEW.NUMERO_FACTURA, 'NUMERO_FACTURA', :NEW.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('FACTURA_PROVEEDOR',:OLD.FECHA, :NEW.FECHA, 'FECHA', :NEW.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('FACTURA_PROVEEDOR', :OLD.MONTO, :NEW.MONTO, 'MONTO', :NEW.ID_FACTURA_PROVEEDOR,  :OLD.ROWID, 'UPDATE'); 
END;




/
ALTER TRIGGER "TRG_FACTURA_PROVEEDOR_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MOV_BANCO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_MOV_BANCO" 
BEFORE INSERT ON MOV_BANCO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('MOV_BANCO', NULL, :NEW.ID_PAGAR_CUENTA, 'ID_PAGAR_CUENTA', :NEW.ID_MOV_BANCO,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('MOV_BANCO', NULL, :NEW.SALDO_ANTERIOR, 'SALDO_ANTERIOR', :NEW.ID_MOV_BANCO,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('MOV_BANCO', NULL, :NEW.SALDO_NUEVO, 'SALDO_NUEVO', :NEW.ID_MOV_BANCO,  :NEW.ROWID, 'INSERT'); 
END;


/
ALTER TRIGGER "TRG_MOV_BANCO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MOV_BANCO_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_MOV_BANCO_DELETE" 
AFTER DELETE ON MOV_BANCO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('MOV_BANCO', :OLD.ID_PAGAR_CUENTA, NULL, 'ID_PAGAR_CUENTA', :OLD.ID_MOV_BANCO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('MOV_BANCO', :OLD.SALDO_ANTERIOR, NULL, 'SALDO_ANTERIOR', :OLD.ID_MOV_BANCO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('MOV_BANCO', :OLD.SALDO_NUEVO, NULL, 'SALDO_NUEVO', :OLD.ID_MOV_BANCO, :OLD.ROWID, 'DELETE'); 
END;


/
ALTER TRIGGER "TRG_MOV_BANCO_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MOV_BANCO_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_MOV_BANCO_UPDATE" 
AFTER UPDATE ON MOV_BANCO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('MOV_BANCO', :OLD.ID_PAGAR_CUENTA, :NEW.ID_PAGAR_CUENTA, 'ID_TIPO_PAGAR_CUENTA', :NEW.ID_MOV_BANCO, :OLD.ROWID, 'UPDATE');
PRC_BITACORA('MOV_BANCO', :OLD.SALDO_ANTERIOR, :NEW.SALDO_ANTERIOR, 'SALDO_ANTERIOR', :NEW.ID_MOV_BANCO, :OLD.ROWID, 'UPDATE');
PRC_BITACORA('MOV_BANCO', :OLD.SALDO_NUEVO, :NEW.SALDO_NUEVO, 'SALDO_NUEVO', :NEW.ID_MOV_BANCO, :OLD.ROWID, 'UPDATE');
END;


/
ALTER TRIGGER "TRG_MOV_BANCO_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ORDEN_COMPRA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_ORDEN_COMPRA" 
BEFORE INSERT ON ORDEN_COMPRA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('ORDEN_COMPRA', NULL, :NEW.ID_PROVEEDOR, 'ID_PROVEEDOR', :NEW.ID_ORDEN_COMPRA, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('ORDEN_COMPRA', NULL, :NEW.ID_PUESTO_EMPLEADO, 'ID_PUESTO_EMPLEADO', :NEW.ID_ORDEN_COMPRA, :NEW.ROWID, 'INSERT');
PRC_BITACORA('ORDEN_COMPRA', NULL, :NEW.FECHA, 'FECHA', :NEW.ID_ORDEN_COMPRA,  :NEW.ROWID, 'INSERT');
PRC_BITACORA('ORDEN_COMPRA', NULL, :NEW.STATUS_APROBACION, 'STATUS_APROBACION', :NEW.ID_ORDEN_COMPRA,  :NEW.ROWID, 'INSERT');
PRC_BITACORA('ORDEN_COMPRA', NULL, :NEW.STATUS_RECEPCION, 'STATUS_RECEPCION', :NEW.ID_ORDEN_COMPRA,  :NEW.ROWID, 'INSERT');
END;

/
ALTER TRIGGER "TRG_ORDEN_COMPRA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ORDEN_COMPRA_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_ORDEN_COMPRA_DELETE" 
AFTER DELETE ON ORDEN_COMPRA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('ORDEN_COMPRA', :OLD.ID_PROVEEDOR, NULL, 'ID_PROVEEDOR', :OLD.ID_ORDEN_COMPRA, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('ORDEN_COMPRA', :OLD.ID_PUESTO_EMPLEADO,  NULL, 'ID_PUESTO_EMPLEADO', :OLD.ID_ORDEN_COMPRA, :OLD.ROWID, 'DELETE');
PRC_BITACORA('ORDEN_COMPRA', :OLD.FECHA,  NULL, 'FECHA', :OLD.ID_ORDEN_COMPRA, :OLD.ROWID, 'DELETE');
PRC_BITACORA('ORDEN_COMPRA', :OLD.STATUS_APROBACION,  NULL, 'STATUS_APROBACION', :OLD.ID_ORDEN_COMPRA, :OLD.ROWID, 'DELETE');
PRC_BITACORA('ORDEN_COMPRA', :OLD.STATUS_RECEPCION,  NULL, 'STATUS_RECEPCION', :OLD.ID_ORDEN_COMPRA, :OLD.ROWID, 'DELETE');
END;

/
ALTER TRIGGER "TRG_ORDEN_COMPRA_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ORDEN_COMPRA_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_ORDEN_COMPRA_UPDATE" 
AFTER UPDATE ON ORDEN_COMPRA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('ORDEN_COMPRA', :OLD.ID_PROVEEDOR, :NEW.ID_PROVEEDOR, 'ID_PROVEEDOR', :NEW.ID_ORDEN_COMPRA, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('ORDEN_COMPRA', :OLD.ID_PUESTO_EMPLEADO, :NEW.ID_PUESTO_EMPLEADO, 'ID_PUESTO_EMPLEADO', :NEW.ID_ORDEN_COMPRA, :OLD.ROWID, 'UPDATE');
PRC_BITACORA('ORDEN_COMPRA', :OLD.FECHA, :NEW.FECHA, 'FECHA', :NEW.ID_ORDEN_COMPRA, :OLD.ROWID, 'UPDATE');
PRC_BITACORA('ORDEN_COMPRA', :OLD.STATUS_APROBACION, :NEW.STATUS_APROBACION, 'STATUS_APROBACION', :NEW.ID_ORDEN_COMPRA, :OLD.ROWID, 'UPDATE');
PRC_BITACORA('ORDEN_COMPRA', :OLD.STATUS_RECEPCION, :NEW.STATUS_RECEPCION, 'STATUS_RECEPCION', :NEW.ID_ORDEN_COMPRA, :OLD.ROWID, 'UPDATE');
END;

/
ALTER TRIGGER "TRG_ORDEN_COMPRA_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PAGAR_CUENTA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PAGAR_CUENTA" 
AFTER INSERT ON PAGAR_CUENTA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
SALDO_BANCO DECIMAL(15,2):= 0;
BEGIN
BEGIN
SELECT SALDO
INTO SALDO_BANCO
FROM CUENTA_BANCO
WHERE ID_CUENTA_BANCO = :NEW.ID_CUENTA_BANCO;

INSERT INTO MOV_BANCO(ID_MOV_BANCO, ID_PAGAR_CUENTA, SALDO_ANTERIOR, SALDO_NUEVO)
    VALUES(SQC_MOV_BANCO.NEXTVAL, :NEW.ID_PAGAR_CUENTA, SALDO_BANCO, (SALDO_BANCO - :NEW.MONTO));
END;
PRC_BITACORA('PAGAR_CUENTA', NULL, :NEW.ID_FORMA_PAGO, 'ID_FORMA_PAGO', :NEW.ID_PAGAR_CUENTA, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('PAGAR_CUENTA', NULL, :NEW.ID_CUENTA_PAGAR, 'ID_CUENTA_PAGAR', :NEW.ID_PAGAR_CUENTA, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('PAGAR_CUENTA', NULL, :NEW.ID_CUENTA_BANCO, 'ID_CUENTA_BANCO', :NEW.ID_PAGAR_CUENTA, :NEW.ROWID, 'INSERT');
PRC_BITACORA('PAGAR_CUENTA', NULL, :NEW.MONTO, 'MONTO', :NEW.ID_PAGAR_CUENTA, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('PAGAR_CUENTA', NULL, :NEW.NUMERO_DOCUMENTO, 'NUMERO_DOCUMENTO', :NEW.ID_PAGAR_CUENTA, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('PAGAR_CUENTA', NULL, :NEW.FECHA, 'FECHA', :NEW.ID_PAGAR_CUENTA, :NEW.ROWID, 'INSERT'); 

 

UPDATE CUENTA_BANCO
   SET SALDO = (SALDO - :NEW.MONTO)
   WHERE ID_CUENTA_BANCO = :NEW.ID_CUENTA_BANCO;

END;
/
ALTER TRIGGER "TRG_PAGAR_CUENTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PAGAR_CUENTA_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PAGAR_CUENTA_DELETE" 
AFTER DELETE ON PAGAR_CUENTA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('PAGAR_CUENTA', :OLD.ID_FORMA_PAGO, NULL, 'ID_FORMA_PAGO', :OLD.ID_PAGAR_CUENTA, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('PAGAR_CUENTA', :OLD.ID_CUENTA_PAGAR, NULL, 'ID_CUENTA_PAGAR', :OLD.ID_PAGAR_CUENTA, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('PAGAR_CUENTA', :OLD.ID_CUENTA_BANCO, NULL, 'ID_CUENTA_BANCO', :OLD.ID_PAGAR_CUENTA, :OLD.ROWID, 'DELETE');
PRC_BITACORA('PAGAR_CUENTA',:OLD.MONTO, NULL, 'MONTO', :OLD.ID_PAGAR_CUENTA, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('PAGAR_CUENTA', :OLD.NUMERO_DOCUMENTO, NULL, 'NUMERO_DOCUMENTO', :OLD.ID_PAGAR_CUENTA, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('PAGAR_CUENTA', :OLD.FECHA, NULL, 'FECHA', :OLD.ID_PAGAR_CUENTA, :OLD.ROWID, 'DELETE'); 

DELETE MOV_BANCO
WHERE ID_PAGAR_CUENTA = :OLD.ID_PAGAR_CUENTA;

UPDATE CUENTA_BANCO
   SET SALDO = (SALDO + :OLD.MONTO)
   WHERE ID_CUENTA_BANCO = :OLD.ID_CUENTA_BANCO;
END;

/
ALTER TRIGGER "TRG_PAGAR_CUENTA_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PAGAR_CUENTA_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PAGAR_CUENTA_UPDATE" 
BEFORE UPDATE ON PAGAR_CUENTA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
SALDO_ANT DECIMAL(15,2):= 0;
BEGIN
BEGIN
SELECT SALDO_ANTERIOR
INTO SALDO_ANT
FROM MOV_BANCO
WHERE ID_PAGAR_CUENTA = :NEW.ID_PAGAR_CUENTA;
END;
PRC_BITACORA('PAGAR_CUENTA', :OLD.ID_FORMA_PAGO, :NEW.ID_FORMA_PAGO, 'ID_FORMA_PAGO', :NEW.ID_PAGAR_CUENTA, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PAGAR_CUENTA', :OLD.ID_CUENTA_PAGAR, :NEW.ID_CUENTA_PAGAR, 'ID_CUENTA_PAGAR', :NEW.ID_PAGAR_CUENTA, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PAGAR_CUENTA', :OLD.ID_CUENTA_BANCO, :NEW.ID_CUENTA_BANCO, 'ID_CUENTA_BANCO', :NEW.ID_PAGAR_CUENTA, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PAGAR_CUENTA',:OLD.MONTO, :NEW.MONTO, 'MONTO', :NEW.ID_PAGAR_CUENTA, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PAGAR_CUENTA', :OLD.NUMERO_DOCUMENTO, :NEW.NUMERO_DOCUMENTO, 'NUMERO_DOCUMENTO', :NEW.ID_PAGAR_CUENTA, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PAGAR_CUENTA', :OLD.FECHA, :NEW.FECHA, 'FECHA', :NEW.ID_PAGAR_CUENTA, :OLD.ROWID, 'UPDATE'); 

UPDATE MOV_BANCO
SET SALDO_NUEVO = (SALDO_ANT -:NEW.MONTO)
WHERE ID_PAGAR_CUENTA = :NEW.ID_PAGAR_CUENTA;

UPDATE CUENTA_BANCO
   SET SALDO = (SALDO + :OLD.MONTO)
   WHERE ID_CUENTA_BANCO = :OLD.ID_CUENTA_BANCO;

UPDATE CUENTA_BANCO
   SET SALDO = (SALDO - :NEW.MONTO)
   WHERE ID_CUENTA_BANCO = :NEW.ID_CUENTA_BANCO;

END;

/
ALTER TRIGGER "TRG_PAGAR_CUENTA_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PERSONA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PERSONA" 
BEFORE INSERT ON PERSONA 
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
NEXISTE NUMBER(1):= 0;
BEGIN
   BEGIN
        SELECT 1  
          INTO NEXISTE
          FROM PERSONA
         WHERE DPI_PERSONA = :NEW.DPI_PERSONA;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN
         --RAISE_APPLICATION_ERROR(-20001,'No existe el DPI buscado');
          NEXISTE :=0;
      WHEN TOO_MANY_ROWS THEN
         RAISE_APPLICATION_ERROR(-20002,'El DPI existe mas de una vez');
      WHEN OTHERS THEN
         RAISE_APPLICATION_ERROR(-20003,'Error al insertar el DPI '||SQLERRM);         
   END;
   IF NEXISTE = 1 THEN
      RAISE_APPLICATION_ERROR(-20005,'El DPI ya esta registrado');
   END IF;
   BEGIN
   PRC_BITACORA('PERSONA', NULL, :NEW.ID_DIRECCION, 'ID_DIRECCION', :NEW.ID_PERSONA, :NEW.ROWID, 'INSERT'); 
   PRC_BITACORA('PERSONA', NULL, :NEW.NOMBRE_PERSONA, 'NOMBRE_PERSONA', :NEW.ID_PERSONA, :NEW.ROWID, 'INSERT');
   PRC_BITACORA('PERSONA', NULL, :NEW.APELLIDO_PERSONA, 'APELLIDO_PERSONA', :NEW.ID_PERSONA, :NEW.ROWID, 'INSERT'); 
   PRC_BITACORA('PERSONA', NULL, :NEW.GENERO, 'GENERO', :NEW.ID_PERSONA, :NEW.ROWID, 'INSERT'); 
   PRC_BITACORA('PERSONA', NULL, :NEW.CORREO_PERSONA, 'CORREO_PERSONA', :NEW.ID_PERSONA, :NEW.ROWID, 'INSERT'); 
   PRC_BITACORA('PERSONA', NULL, :NEW.DPI_PERSONA, 'DPI_PERSONA', :NEW.ID_PERSONA, :NEW.ROWID, 'INSERT'); 
   PRC_BITACORA('PERSONA', NULL, :NEW.NIT_PERSONA, 'NIT_PERSONA', :NEW.ID_PERSONA, :NEW.ROWID, 'INSERT'); 
   PRC_BITACORA('PERSONA', NULL, :NEW.TELEFONO, 'TELEFONO', :NEW.ID_PERSONA, :NEW.ROWID, 'INSERT'); 
   END; 
END;




/
ALTER TRIGGER "TRG_PERSONA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PERSONA_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PERSONA_DELETE" 
AFTER DELETE ON PERSONA 
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
    BEGIN
   PRC_BITACORA('PERSONA', :OLD.ID_DIRECCION, NULL, 'ID_DIRECCION', :OLD.ID_PERSONA, :OLD.ROWID, 'DELETE'); 
   PRC_BITACORA('PERSONA', :OLD.NOMBRE_PERSONA,  NULL, 'NOMBRE_PERSONA', :OLD.ID_PERSONA,:OLD.ROWID, 'DELETE');
   PRC_BITACORA('PERSONA',:OLD.APELLIDO_PERSONA, NULL, 'APELLIDO_PERSONA', :OLD.ID_PERSONA, :OLD.ROWID, 'DELETE'); 
   PRC_BITACORA('PERSONA',:OLD.GENERO,  NULL, 'GENERO', :OLD.ID_PERSONA,:OLD.ROWID, 'DELETE'); 
   PRC_BITACORA('PERSONA',  :OLD.CORREO_PERSONA,  NULL, 'CORREO_PERSONA', :OLD.ID_PERSONA,:OLD.ROWID, 'DELETE'); 
   PRC_BITACORA('PERSONA',:OLD.DPI_PERSONA,  NULL, 'DPI_PERSONA', :OLD.ID_PERSONA, :OLD.ROWID, 'DELETE'); 
   PRC_BITACORA('PERSONA',:OLD.NIT_PERSONA,  NULL, 'NIT_PERSONA', :OLD.ID_PERSONA, :OLD.ROWID, 'DELETE'); 
   PRC_BITACORA('PERSONA',:OLD.TELEFONO,  NULL, 'TELEFONO', :OLD.ID_PERSONA, :OLD.ROWID, 'DELETE'); 
   END; 
END;




/
ALTER TRIGGER "TRG_PERSONA_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PERSONA_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PERSONA_UPDATE" 
BEFORE UPDATE ON PERSONA 
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
    BEGIN
   PRC_BITACORA('PERSONA', :OLD.ID_DIRECCION, :NEW.ID_DIRECCION, 'ID_DIRECCION', :NEW.ID_PERSONA, :OLD.ROWID, 'UPDATE'); 
   PRC_BITACORA('PERSONA', :OLD.NOMBRE_PERSONA, :NEW.NOMBRE_PERSONA, 'NOMBRE_PERSONA', :NEW.ID_PERSONA,:OLD.ROWID, 'UPDATE');
   PRC_BITACORA('PERSONA',:OLD.APELLIDO_PERSONA, :NEW.APELLIDO_PERSONA, 'APELLIDO_PERSONA', :NEW.ID_PERSONA, :OLD.ROWID, 'UPDATE'); 
   PRC_BITACORA('PERSONA',:OLD.GENERO, :NEW.GENERO, 'GENERO', :NEW.ID_PERSONA,:OLD.ROWID, 'UPDATE'); 
   PRC_BITACORA('PERSONA',  :OLD.CORREO_PERSONA, :NEW.CORREO_PERSONA, 'CORREO_PERSONA', :NEW.ID_PERSONA,:OLD.ROWID, 'UPDATE'); 
   PRC_BITACORA('PERSONA',:OLD.DPI_PERSONA, :NEW.DPI_PERSONA, 'DPI_PERSONA', :NEW.ID_PERSONA, :OLD.ROWID, 'UPDATE'); 
   PRC_BITACORA('PERSONA',:OLD.NIT_PERSONA, :NEW.NIT_PERSONA, 'NIT_PERSONA', :NEW.ID_PERSONA, :OLD.ROWID, 'UPDATE'); 
   PRC_BITACORA('PERSONA',:OLD.TELEFONO, :NEW.TELEFONO, 'TELEFONO', :NEW.ID_PERSONA, :OLD.ROWID, 'UPDATE'); 
   END; 
END; 




/
ALTER TRIGGER "TRG_PERSONA_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PRODUCTO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PRODUCTO" 
BEFORE INSERT ON PRODUCTO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('PRODUCTO', NULL, :NEW.NOMBRE_PRODUCTO, 'NOMBRE_PRODUCTO', :NEW.ID_PRODUCTO, :NEW.ROWID, 'INSERT'); 
END;




/
ALTER TRIGGER "TRG_PRODUCTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PRODUCTO_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PRODUCTO_DELETE" 
AFTER DELETE ON PRODUCTO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
BEGIN
PRC_BITACORA('PRODUCTO', :OLD.NOMBRE_PRODUCTO, NULL, 'NOMBRE_PRODUCTO', :OLD.ID_PRODUCTO, :OLD.ROWID, 'DELETE'); 
END;
END;




/
ALTER TRIGGER "TRG_PRODUCTO_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PRODUCTO_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PRODUCTO_UPDATE" 
AFTER UPDATE ON PRODUCTO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('PRODUCTO', :OLD.NOMBRE_PRODUCTO, :NEW.NOMBRE_PRODUCTO, 'NOMBRE_PRODUCTO', :NEW.ID_PRODUCTO, :OLD.ROWID, 'UPDATE'); 
END;




/
ALTER TRIGGER "TRG_PRODUCTO_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PROVEEDOR
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PROVEEDOR" 
BEFORE INSERT ON PROVEEDOR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('PROVEEDOR', NULL, :NEW.ID_TIPO_PROVEEDOR, 'ID_TIPO_PROVEEDOR', :NEW.ID_PROVEEDOR, :NEW.ROWID, 'INSERT'); 

PRC_BITACORA('PROVEEDOR', NULL, :NEW.ID_DIRECCION, 'ID_DIRECCION', :NEW.ID_PROVEEDOR, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('PROVEEDOR', NULL, :NEW.NOMBRE_PROVEEDOR, 'NOMBRE_PROVEEDOR', :NEW.ID_PROVEEDOR, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('PROVEEDOR', NULL, :NEW.NIT_PROVEEDOR, 'NIT_PROVEEDOR', :NEW.ID_PROVEEDOR, :NEW.ROWID, 'INSERT'); 
END;



/
ALTER TRIGGER "TRG_PROVEEDOR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PROVEEDOR_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PROVEEDOR_DELETE" 
AFTER DELETE ON PROVEEDOR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('PROVEEDOR',:OLD.ID_TIPO_PROVEEDOR, NULL, 'ID_TIPO_PROVEEDOR', :OLD.ID_PROVEEDOR, :OLD.ROWID, 'DELETE'); 

PRC_BITACORA('PROVEEDOR',:OLD.ID_DIRECCION, NULL, 'ID_DIRECCION', :OLD.ID_PROVEEDOR,  :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('PROVEEDOR', :OLD.NOMBRE_PROVEEDOR, NULL, 'NOMBRE_PROVEEDOR', :OLD.ID_PROVEEDOR, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('PROVEEDOR',:OLD.NIT_PROVEEDOR, NULL, 'NIT_PROVEEDOR', :OLD.ID_PROVEEDOR,  :OLD.ROWID, 'DELETE'); 
END;



/
ALTER TRIGGER "TRG_PROVEEDOR_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PROVEEDOR_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PROVEEDOR_UPDATE" 
AFTER UPDATE ON PROVEEDOR
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('PROVEEDOR',:OLD.ID_TIPO_PROVEEDOR, :NEW.ID_TIPO_PROVEEDOR, 'ID_TIPO_PROVEEDOR', :NEW.ID_PROVEEDOR, :OLD.ROWID, 'UPDATE'); 

PRC_BITACORA('PROVEEDOR',:OLD.ID_DIRECCION, :NEW.ID_DIRECCION, 'ID_DIRECCION', :NEW.ID_PROVEEDOR,  :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PROVEEDOR', :OLD.NOMBRE_PROVEEDOR, :NEW.NOMBRE_PROVEEDOR, 'NOMBRE_PROVEEDOR', :NEW.ID_PROVEEDOR, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PROVEEDOR',:OLD.NIT_PROVEEDOR, :NEW.NIT_PROVEEDOR, 'NIT_PROVEEDOR', :NEW.ID_PROVEEDOR,  :OLD.ROWID, 'UPDATE'); 
END;



/
ALTER TRIGGER "TRG_PROVEEDOR_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PUESTO_EMPLEADO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PUESTO_EMPLEADO" 
BEFORE INSERT ON PUESTO_EMPLEADO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('PUESTO_EMPLEADO', NULL, :NEW.ID_PUESTO, 'ID_PUESTO', :NEW.ID_PUESTO_EMPLEADO, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('PUESTO_EMPLEADO', NULL, :NEW.ID_EMPLEADO, 'ID_EMPLEADO', :NEW.ID_PUESTO_EMPLEADO, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('PUESTO_EMPLEADO', NULL, :NEW.FECHA_INICIO, 'FECHA_INICIO', :NEW.ID_PUESTO_EMPLEADO, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('PUESTO_EMPLEADO', NULL, :NEW.FECHA_FIN, 'FECHA_FIN', :NEW.ID_PUESTO_EMPLEADO, :NEW.ROWID, 'INSERT'); 
END;

/
ALTER TRIGGER "TRG_PUESTO_EMPLEADO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PUESTO_EMPLEADO_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PUESTO_EMPLEADO_DELETE" 
AFTER DELETE ON PUESTO_EMPLEADO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('PUESTO_EMPLEADO',:OLD.ID_PUESTO, NULL, 'ID_PUESTO', :OLD.ID_PUESTO_EMPLEADO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('PUESTO_EMPLEADO', :OLD.ID_EMPLEADO, NULL, 'ID_EMPLEADO', :OLD.ID_PUESTO_EMPLEADO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('PUESTO_EMPLEADO', :OLD.FECHA_INICIO, NULL, 'FECHA_INICIO', :OLD.ID_PUESTO_EMPLEADO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('PUESTO_EMPLEADO', :OLD.FECHA_FIN, NULL, 'FECHA_FIN', :OLD.ID_PUESTO_EMPLEADO, :OLD.ROWID, 'DELETE'); 
END;

/
ALTER TRIGGER "TRG_PUESTO_EMPLEADO_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PUESTO_EMPLEADO_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_PUESTO_EMPLEADO_UPDATE" 
AFTER UPDATE ON PUESTO_EMPLEADO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('PUESTO_EMPLEADO',:OLD.ID_PUESTO, :NEW.ID_PUESTO, 'ID_PUESTO', :NEW.ID_PUESTO_EMPLEADO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PUESTO_EMPLEADO', :OLD.ID_EMPLEADO, :NEW.ID_EMPLEADO, 'ID_EMPLEADO', :NEW.ID_PUESTO_EMPLEADO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PUESTO_EMPLEADO', :OLD.FECHA_INICIO, :NEW.FECHA_INICIO, 'FECHA_INICIO', :NEW.ID_PUESTO_EMPLEADO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('PUESTO_EMPLEADO', :OLD.FECHA_FIN, :NEW.FECHA_FIN, 'FECHA_FIN', :NEW.ID_PUESTO_EMPLEADO, :OLD.ROWID, 'UPDATE'); 
END;

/
ALTER TRIGGER "TRG_PUESTO_EMPLEADO_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEPCION
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_RECEPCION" 
BEFORE INSERT ON RECEPCION
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('RECEPCION', NULL, :NEW.ID_PUESTO_EMPLEADO, 'ID_PUESTO_EMPLEADO', :NEW.ID_RECEPCION, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('RECEPCION', NULL, :NEW.NUMERO_ENVIO, 'NUMERO_ENVIO', :NEW.ID_RECEPCION, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('RECEPCION', NULL, :NEW.FECHA, 'FECHA', :NEW.ID_RECEPCION, :NEW.ROWID, 'INSERT'); 
END;




/
ALTER TRIGGER "TRG_RECEPCION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEPCION_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_RECEPCION_DELETE" 
AFTER DELETE ON RECEPCION
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('RECEPCION',:OLD.ID_PUESTO_EMPLEADO,NULL, 'ID_PUESTO_EMPLEADO', :OLD.ID_RECEPCION, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('RECEPCION',:OLD.NUMERO_ENVIO, NULL, 'NUMERO_ENVIO', :OLD.ID_RECEPCION, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('RECEPCION', :OLD.FECHA, NULL, 'FECHA', :OLD.ID_RECEPCION, :OLD.ROWID, 'DELETE'); 
END;




/
ALTER TRIGGER "TRG_RECEPCION_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEPCION_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_RECEPCION_UPDATE" 
AFTER UPDATE ON RECEPCION
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('RECEPCION',:OLD.ID_PUESTO_EMPLEADO, :NEW.ID_PUESTO_EMPLEADO, 'ID_PUESTO_EMPLEADO', :NEW.ID_RECEPCION, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('RECEPCION',:OLD.NUMERO_ENVIO, :NEW.NUMERO_ENVIO, 'NUMERO_ENVIO', :NEW.ID_RECEPCION, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('RECEPCION', :OLD.FECHA, :NEW.FECHA, 'FECHA', :NEW.ID_RECEPCION, :OLD.ROWID, 'UPDATE'); 
END;




/
ALTER TRIGGER "TRG_RECEPCION_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SERVICIO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_SERVICIO" 
BEFORE INSERT ON SERVICIO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('SERVICIO', NULL, :NEW.ID_PROVEEDOR, 'ID_PROVEEDOR', :NEW.ID_SERVICIO, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('SERVICIO', NULL, :NEW.ID_PUESTO_EMPLEADO, 'ID_PUESTO_EMPLEADO', :NEW.ID_SERVICIO, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('SERVICIO', NULL, :NEW.NOMBRE_SERVICIO, 'NOMBRE_SERVICIO', :NEW.ID_SERVICIO, :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('SERVICIO', NULL, :NEW.PRECIO, 'PRECIO', :NEW.ID_SERVICIO, :NEW.ROWID, 'INSERT'); 
END;




/
ALTER TRIGGER "TRG_SERVICIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SERVICIO_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_SERVICIO_DELETE" 
AFTER DELETE ON SERVICIO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('SERVICIO', :OLD.ID_PROVEEDOR, NULL, 'ID_PROVEEDOR', :OLD.ID_SERVICIO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('SERVICIO', :OLD.ID_PUESTO_EMPLEADO,NULL, 'ID_PUESTO_EMPLEADO', :OLD.ID_SERVICIO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('SERVICIO', :OLD.NOMBRE_SERVICIO, NULL, 'NOMBRE_SERVICIO', :OLD.ID_SERVICIO, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('SERVICIO', :OLD.PRECIO, NULL, 'PRECIO', :OLD.ID_SERVICIO, :OLD.ROWID, 'DELETE'); 
END;




/
ALTER TRIGGER "TRG_SERVICIO_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SERVICIO_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_SERVICIO_UPDATE" 
AFTER UPDATE ON SERVICIO
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('SERVICIO', :OLD.ID_PROVEEDOR, :NEW.ID_PROVEEDOR, 'ID_PROVEEDOR', :NEW.ID_SERVICIO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('SERVICIO', :OLD.ID_PUESTO_EMPLEADO, :NEW.ID_PUESTO_EMPLEADO, 'ID_PUESTO_EMPLEADO', :NEW.ID_SERVICIO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('SERVICIO', :OLD.NOMBRE_SERVICIO, :NEW.NOMBRE_SERVICIO, 'NOMBRE_SERVICIO', :NEW.ID_SERVICIO, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('SERVICIO', :OLD.PRECIO, :NEW.PRECIO, 'PRECIO', :NEW.ID_SERVICIO, :OLD.ROWID, 'UPDATE'); 
END;




/
ALTER TRIGGER "TRG_SERVICIO_UPDATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SUCURSAL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_SUCURSAL" 
BEFORE INSERT ON SUCURSAL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('SUCURSAL', NULL, :NEW.ID_DIRECCION, 'ID_DIRECCION', :NEW.ID_SUCURSAL,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('SUCURSAL', NULL, :NEW.ID_TIPO_SUCURSAL, 'ID_TIPO_SUCURSAL', :NEW.ID_SUCURSAL,  :NEW.ROWID, 'INSERT'); 
PRC_BITACORA('SUCURSAL', NULL, :NEW.NOMBRE_SUCURSAL, 'NOMBRE_SUCURSAL', :NEW.ID_SUCURSAL, :NEW.ROWID, 'INSERT'); 
END;




/
ALTER TRIGGER "TRG_SUCURSAL" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SUCURSAL_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_SUCURSAL_DELETE" 
AFTER DELETE ON SUCURSAL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('SUCURSAL', :OLD.ID_DIRECCION, NULL, 'ID_DIRECCION', :OLD.ID_SUCURSAL, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('SUCURSAL', :OLD.ID_TIPO_SUCURSAL, NULL, 'ID_TIPO_SUCURSAL', :OLD.ID_SUCURSAL, :OLD.ROWID, 'DELETE'); 
PRC_BITACORA('SUCURSAL', :OLD.NOMBRE_SUCURSAL, NULL, 'NOMBRE_SUCURSAL', :OLD.ID_SUCURSAL, :OLD.ROWID, 'DELETE'); 
END;





/
ALTER TRIGGER "TRG_SUCURSAL_DELETE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_SUCURSAL_UPDATE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_SUCURSAL_UPDATE" 
AFTER UPDATE ON SUCURSAL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
PRC_BITACORA('SUCURSAL', :OLD.ID_DIRECCION, :NEW.ID_DIRECCION, 'ID_DIRECCION', :NEW.ID_SUCURSAL, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('SUCURSAL', :OLD.ID_TIPO_SUCURSAL, :NEW.ID_TIPO_SUCURSAL, 'ID_TIPO_SUCURSAL', :NEW.ID_SUCURSAL, :OLD.ROWID, 'UPDATE'); 
PRC_BITACORA('SUCURSAL', :OLD.NOMBRE_SUCURSAL, :NEW.NOMBRE_SUCURSAL, 'NOMBRE_SUCURSAL', :NEW.ID_SUCURSAL, :OLD.ROWID, 'UPDATE'); 
END;




/
ALTER TRIGGER "TRG_SUCURSAL_UPDATE" ENABLE;
